[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "roarm-ik"
version = "1.1.4"
authors = [
    { name = "Hudson Reeves", email = "hreeve01@uafs.edu" }
]
description = "A Python library for the WaveShare Ro-arm m3 adding inverse kinematics functionality wrapping the roarmsdk"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    # Add any dependencies your library needs here, for example:
    # "numpy",
]

[tool.setuptools.packages.find]
where = ["."]  # Tells it to look for your Python package folder in the root
